### ISSUE TITLE
Release 1.0.11

### ISSUE THREAD

**Issue by Perdu** [mbacarella/curses#11]
Hello,
Can you create a release for 1.0.11, so I can update the arch linux package?
(There currently is a build issue, not sure if it's already handled by the latest commits)

**Comment by mbacarella** [comment]
I'm attempting to do this but opam release keeps giving me unhelpful
errors. Will get to the bottom of this soon.

**Comment by Perdu** [comment]
Hello, any update on this?

**Comment by mbacarella** [comment]
I get this error when I try `opam publish`.

```
Fetching the package repository, this may take a while...
[ERROR] Uncaught exception: "/usr/bin/git commit -m Package curses.1.0.11" exited with code 1
```

My strategy of waiting for stuff to fix itself has failed. Let me ping support channels.

**Comment by mbacarella** [comment]
@Perdu do you want to try to release this? Just clone it and try `opam publish`?

I've tried two different opam environments on two different machines and am having no luck.

**Comment by Perdu** [comment]
For some reason, I get `[ERROR] HTTP Error 404 Not Found` when trying to fork (I don't know what it's failing to load though).
I can't help more than this, I don't know anything about opam

**Comment by Perdu** [comment]
ping
Any update on this?

**Comment by Perdu** [comment]
Done: https://github.com/ocaml/opam-repository/pull/24410

**Comment by Perdu** [comment]
opam-repository maintainers ask for the reason for the `opam publish`.
I'm a bit confused too. Why isn't 1.0.11 a release on github? There is an archive already. Using that for packaging for the moment.

**Comment by mbacarella** [comment]
Oh. That's weird. I don't know why there isn't a 1.0.11 release on github. `opam publish` is supposed to do that, I assume.

**Comment by mbacarella** [comment]
I guess I thought you meant do an *opam* release when you said create a release, but you were saying just create a github release.

**Comment by mbacarella** [comment]
So, if I had known more about Arch Linux this might have been less confusing. Whoops! Anyway! Release created: https://github.com/mbacarella/curses/releases/tag/1.0.11

Re-open if I missed anything.
