### ISSUE TITLE
Building fails on archlinux because of curses.h packaging

### ISSUE THREAD

**Issue by Perdu** [mbacarella/curses#4]
Hello,

Since the removal of the previous build system in e5f6c37, building fails in archlinux (see trace below).
The issue is that archlinux builds ncurses in a different way, and the ncursesw/ folder is not used. Not sure if `<curses.h>` is sufficient, or if `<cursesw.h>` should be used.

See a discussion about this in another repository: https://github.com/rakshasa/rtorrent/issues/886

Could this case be added back to the build system?

Trace when installing with opam:
```bash
[ERROR] The compilation of curses.1.0.9 failed at "dune build -p curses -j 3 @install".                                                                                                                                                       
#=== ERROR while compiling curses.1.0.9 =======================================#                                       # context              2.1.1 | linux/x86_64 | ocaml.4.12.0 | https://opam.ocaml.org#255e47c6
# path                 ~/.opam/default/.opam-switch/build/curses.1.0.9
# command              ~/.opam/default/bin/dune build -p curses -j 3 @install                                          # exit-code            1                                   
# env-file             ~/.opam/log/curses-1221-0bdc36.env                                                              # output-file          ~/.opam/log/curses-1221-0bdc36.out
### output ###                                                                                                         #          gcc ml_curses.o (exit 1)
# (cd _build/default && /usr/sbin/gcc -O2 -fno-strict-aliasing -fwrapv -fPIC -march=x86-64 -mtune=generic -O2 -pipe -fn
o-plt -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_FORTIFY_SOURCE=2 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DHAVE_CONFIG_H -g 
-I /usr/lib/ocaml -o ml_curses.o -c ml_curses.c)
# In file included from ml_curses.c:2:
# config.h:1:23: fatal error: ncursesw/curses.h: No such file or directory                           
#     1 | #define CURSES_HEADER <ncursesw/curses.h>
#       |                       ^                   
```

**Comment by mbacarella** [comment]
Could you point me at an Arch Linux docker image (version) that matches your system?

**Comment by Perdu** [comment]
Arch Linux is a rolling release distribution, so archlinux:latest will do fine

**Comment by mbacarella** [comment]
Should be fixed. Before I do a release, are you able to opam pin the package against [this PR](https://github.com/mbacarella/curses/pull/5) and give it a try?

**Comment by Perdu** [comment]
LGTM, thanks! Waiting for the release to opam for another project

**Comment by mbacarella** [comment]
Preparing a new release now. What do you use ocaml curses for, out of total curiosity?

**Comment by Perdu** [comment]
Thanks! We're maintaining wyrd, an old but good calendar software, see https://gitlab.com/wyrd-calendar/wyrd/ (or screenshots here https://github.com/perdu/wyrd)

**Comment by mbacarella** [comment]
Neato @ wyrd.

You can track the new curses release status here: https://github.com/ocaml/opam-repository/pull/20074
