### ISSUE TITLE
Could this package look for ncursesw?

### ISSUE THREAD

**Issue by LAC-Tech** [mbacarella/curses#6]
Fails to build on my system because it tries to run `pkg-config ncurses`.

Any chance it could look for ncursesw? Which is probably what most people want, but some distros don't symlink ncurses to ncursesw

**Comment by mbacarella** [comment]
What platform is this, by chance?

**Comment by mbacarella** [comment]
Also, could you paste the full failure message?

**Comment by LAC-Tech** [comment]
Void Linux [0].

```
[NOTE] External dependency handling not supported for OS family 'void'.
       You can disable this check using 'opam option --global depext=false'
The following actions will be performed:
  - install conf-ncurses 1      [required by curses]
  - install curses       1.0.10
===== 2 to install =====
Do you want to continue? [Y/n] y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> retrieved curses.1.0.10  (cached)
[ERROR] The compilation of conf-ncurses.1 failed at "pkg-config ncurses".

#=== ERROR while compiling conf-ncurses.1 =====================================#
# context     2.1.2 | linux/x86_64 | ocaml-base-compiler.4.13.1 | https://opam.ocaml.org#0320214b
# path        ~/.opam/4.13.1/.opam-switch/build/conf-ncurses.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build pkg-config ncurses
# exit-code   1
# env-file    ~/.opam/log/conf-ncurses-4894-1213b1.env
# output-file ~/.opam/log/conf-ncurses-4894-1213b1.out



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build conf-ncurses 1
+-
- No changes have been performed
```

[0] Made an issue a year or so back, their TL;DR is it's upstreams fault - don't shoot the messenger!

https://github.com/void-linux/void-packages/issues/32987

**Comment by mbacarella** [comment]
I see. Ironically, this project,`curses` actually does probe for `pkg-config ncursesw` to get build information. It's `conf-ncurses`, a dependency of this project, that probes for `ncurses`. You can see what it does for each platform here:

https://github.com/ocaml/opam-repository/blob/master/packages/conf-ncurses/conf-ncurses.1/opam

I also see you've reported this against opam-repository. I'm going to follow up here:
 https://github.com/ocaml/opam-repository/issues/19600

opam-repository is the right place to have this discussion. `curses` is just one of several packages that depends on `conf-ncurses`, and more importantly, I'm not the maintainer of that. :)

**Comment by mbacarella** [comment]
To be clear I think this would build on Void Linux if conf-ncurses applied a fix, so I'm consdiering this issue closed here.
